### ISSUE TITLE
Support SKOS mapping relations

### ISSUE THREAD

**Issue by acka47** [skohub-io/skohub-vocabs#109]
`skos:broadMatch`, `skos:exactMatch`, `skos:closeMatch`, `skos:narrowMatch`, `skos:relatedMatch`

**Comment by sroertgen** [comment]
Picking up my question from #116:

- should we also add relatedMatch to a Concept's html-site, like done in #106?

I opened a pull request in #117 to add `skos:relatedMatch`. I could extend it to include the other mentioned ones as well, if the implementation of `skos:relatedMatch` is ok for everyone.

**Comment by acka47** [comment]
Unintentionall merged into master, still to be reviewed.

**Comment by acka47** [comment]
Looks fine now on test. +1

**Comment by acka47** [comment]
Deployed to production. Closing.
