### ISSUE TITLE
Add JSON-LD to vocab overview page

### ISSUE THREAD

**Issue by acka47** [skohub-io/skohub-vocabs#110]
The overview pages listing vocabularies from a connected repo (like [here](https://vocabs.openeduhub.de/) or [here](https://skohub.io/hbz/vocabs-edu/heads/master/)) could use some structured data. As we are already using ActivityStreams, we might use [`as:Collection`](https://www.w3.org/TR/activitystreams-core/#collection) for this. Also, [Hydra collections](http://www.hydra-cg.com/spec/latest/core/#collections) come to mind.

**Comment by sebilasse** [comment]
> [as:Collection](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-collection) or [as:OrderedCollection](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-orderedcollection)

I would also like to suggest a thing to make it more ActivityPub friendly.
This goes for the creation of according JSON-LD.
It should have all of the defined things in the concept and we could alias `skos:prefLabel` as `as:name` or `as:nameMap` and the `skos:definition` as `as:summary` or `as:summaryMap` and then anyone can use it for e.g. `as:Relationship` …

**Comment by acka47** [comment]
Thanks for the suggestions, @sebilasse . As this issue is about the overview pages (like [here](https://vocabs.openeduhub.de/) or [here](https://skohub.io/hbz/vocabs-edu/heads/master/)) for all the vocabs in an associated GitHub repo, we should keep your propoasal in mind when re-introducing inboxes and ActivityStreams vocabulary for songle concepts later this year. But first, we will soon temporarily remove inboxes and AS information with #171.

**Comment by sebilasse** [comment]
+1 
> But first, we will soon temporarily remove inboxes and AS information
yes, I knew this. I have to think a bit – also tempted to quickly friendly fork this and work on it for a while :)

**Comment by acka47** [comment]
Closing as we first have to discuss the overview page itself, see #231 .
