### ISSUE TITLE
Add link to JSON-LD for each page

### ISSUE THREAD

**Issue by acka47** [skohub-io/skohub-vocabs#111]
Put a small ![](https://json-ld.org/images/json-ld-data-24.png) somewhere for each concept and scheme that links to the `.json` representatiob of each resource.

**Comment by sroertgen** [comment]
Hey @literarymachine,

I just wanted to work on this and saw you already created a branch for this issue. I just added the little png @acka47 wanted there. I also had to add a `file-mock.js` in the `__mocks__`-folder like suggested here: <https://jestjs.io/docs/en/webpack.html#handling-static-assets> to get the test run through.

Is this ok for you? If so we could open a pull request.

**Comment by literarymachine** [comment]
> Is this ok for you? If so we could open a pull request.

Sure thing, see #119!

**Comment by dr0i** [comment]
As #119 is merged, this issue may be fixed. Please close it then, @acka47 .
