### ISSUE TITLE
Information missing in vocabs with hash URIs

### ISSUE THREAD

**Issue by acka47** [skohub-io/skohub-vocabs#122]
Originates from https://github.com/skohub-io/skohub-vocabs/pull/120#issuecomment-765678384

As only the `ConceptScheme` JSON is built in case of a hash URI vocab and only few fields are considered there (`id`, `notation`, `prefLabel`, `narrower`), information like `broader`, `related` or `altLabel` is missing (see e.g. https://github.com/acka47/nwbib-spatial/commit/00703e03d78eb0cfd3a0c3d398459b448bd37fe1 & https://test.skohub.io/acka47/nwbib-spatial/heads/master/nwbib.de/spatial.json).

We should think about how to add this to the `ConceptScheme` JSON of a hash URI vocab without blowing up the `ConceptSchem` JSON of a slash URI (where all the `Concept` information can be found at the repective URI for the Concept).

**Comment by sroertgen** [comment]
@acka47 Which kind of information do you think should be given for Hash URI concepts? 

Currently it is:
- `id`
- `notation`
- `prefLabel`
- `altLabel`
- `narrower`

Should it be totally the same as for hashURIs?
Then we have to do quite some changes in the build process I think. But should be possible.

**Comment by acka47** [comment]
> Should it be totally the same as for hashURIs?

This was the general approach, yes.. But I think it is ok to prioritize this low as we apparently don't have people using SkoHub Vocabs with Hash URIs. We might as well think about requiring the use slash URIs...

**Comment by sroertgen** [comment]
Do we want to close this then in favor of #236 ? We could add a note in the README that if somebody has the requirement for hash URIs, you should open a ticket?

**Comment by acka47** [comment]
> Do we want to close this then in favor of https://github.com/skohub-io/skohub-vocabs/issues/236 ? 

+1

> We could add a note in the README that if somebody has the requirement for hash URIs, you should open a ticket?

+1
