### ISSUE TITLE
Support skos:example

### ISSUE THREAD

**Issue by acka47** [skohub-io/skohub-vocabs#124]
Requirement by IBI for "Klassifikation für interdisziplinäre Forschungsfelder", sent by V.P. via email (to @acka47 & @sroertgen) today (2021-01-28).

**Comment by sroertgen** [comment]
How do we want handle `skos:example`? I think SKOS allows multiple examples per language (which I guess makes sense). Though for other documentation properties, e.g. `skos:scopeNote` or `skos:definition`, we right now only support one value per language (where SKOS would also allow more than one).

**Comment by acka47** [comment]
Good question. You mean whether we should use an array here, right? As `skos::example` is a subproperty of `skos:note` we should treat it the same. The use case comes from https://github.com/KDSF-FFK/KDSF-FFK/blob/main/FFK.ttl where several examples are listed in one string and not separate ones. This is in line with our current approach to `skos:note`.

**Comment by sroertgen** [comment]
>[...] You mean whether we should use an array here, right? 

Yes.

> As `skos::example` is a subproperty of `skos:note` we should treat it the same. [...] This is in line with our current approach to `skos:note`.

I think we currently only allow one language per value:

https://github.com/skohub-io/skohub-vocabs/blob/4bd7051d3cdb34d422a74d801ac45d264f8cfe6b/src/context.js#L45-L53

The only exception is `skos:altLabel`:

https://github.com/skohub-io/skohub-vocabs/blob/4bd7051d3cdb34d422a74d801ac45d264f8cfe6b/src/context.js#L42-L44

I just made a quick  test with two `skos:definition` of same language and it did not work, no definition at all showed up though it did build successfully.

**Comment by sroertgen** [comment]
Ah sorry. I got it wrong. Yes, one long string per language is totally fine. And it is in line with the current approach.

**Comment by dr0i** [comment]
PR is merged, but this issue is not closed automatically, while I think it could be closed.
As it is unassigned, I hereby assign it to @acka47  who inititated the issue.
