### ISSUE TITLE
Not all skos:prefLabels are indexed in FlexSearch

### ISSUE THREAD

**Issue by acka47** [skohub-io/skohub-vocabs#127]
Taking a deeper look at the FlexSearch index of some vocabularies, I noticed that not all `skos:prefLabels` are indexed. In HCRT, I found that "Abbildung" from https://w3id.org/kim/hcrt/image isn't indexed:

![image](https://user-images.githubusercontent.com/160292/107194740-bbdfb580-69f0-11eb-88d8-50ff679fe480.png)

**Comment by literarymachine** [comment]
![image](https://user-images.githubusercontent.com/149825/107228828-6372dd00-6a1d-11eb-8d5f-64e4825f48f2.png)

Confirmed, it looks like the problem is that one language overwrites the others.

**Comment by sroertgen** [comment]
What is the wanted behaviour here? Do we also want to show results if search term was in another language? There maybe two options:

1. Show Concepts even if the search term is another language:

![Screenshot 2021-09-02 at 10 19 43](https://user-images.githubusercontent.com/18149685/131810202-41ddbc2c-024e-413b-9715-f0c8c9004dd6.png)
![Screenshot 2021-09-02 at 10 19 54](https://user-images.githubusercontent.com/18149685/131810206-8301b217-3b3c-4501-a8bf-4d2916208b39.png)

2. Only show results for the given language:

![Screenshot 2021-09-02 at 10 27 50](https://user-images.githubusercontent.com/18149685/131810278-b93405d0-d585-4e03-867a-25f8cb52a5d2.png)
![Screenshot 2021-09-02 at 10 27 56](https://user-images.githubusercontent.com/18149685/131810277-5b771bbf-1403-4b6e-ad75-89fb15679f82.png)

I think the first approach might be a bit confusing for users, but I'm open for discussion and feedback.

**Comment by acka47** [comment]
We should also consider #128 ("Add strings from skos:altLabel & skos:example to FlexSearch index") in this discussion as implementing it might also lead to showing a concept label as result that does not match the search term. When broadening the context like this, I also see two options:

1. Show concepts if the search term matches `prefLabel`, `altLabel` or `example` in the chosen language. (The question why this concept is shown as result will then be answered when clicking on the link where `altLabel`s and `example`s are shown.)
2.  Show concepts if the search term matches `prefLabel`, `altLabel` or `example` in any language.

I think, here, the first approach makes more sense, i.e. to even show a concept when the search term matches its `prefLabel`, `altLabel` or `example` in the given language.

This would mean, for this issue, to chose your second approach from https://github.com/skohub-io/skohub-vocabs/issues/127#issuecomment-911383856 which you already favoured.

**Comment by acka47** [comment]
I rebuilt [HCRT](https://w3id.org/kim/hcrt/scheme) and [Hochschulfächersystematik](). Closing.
