### ISSUE TITLE
Add strings from skos:altLabel & skos:example to FlexSearch index 

### ISSUE THREAD

**Issue by acka47** [skohub-io/skohub-vocabs#128]
Requested by V.P. via email on 2021-02-21:

> Die Suchfunktion ist ein tolles Feature der 
> Visualisierung, die Suche sucht aber nur in den Klassenbezeichnungen und 
> nicht in den Scope Notes und Examples. Ist dies mit Absicht so gewählt 
> oder einfach schwieriger zu implementieren? Die Frage kam deshalb auf, 
> weil bei unserer Klassifikation das Szenario durchaus gesehen wird, dass 
> die Nutzenden ein Wort aus den Examples eingeben, um zu suchen, in 
> welcher Klasse dies ist.

It looks like that currently the FlexSearch index is only built from `skos:prefLabel` in all languages that are provided (although there seem to be some problems with this, see #127). The use case to find concepts via `altLabel` or `example` definitely makes sense to me.

**Comment by ghertko** [comment]
> ... The use case to find concepts via `altLabel` or `example` definitely makes sense to me.
Oh, yes, it would be good to have this feature. Then the content of `altLabel` should also be visible on the concept's page.

**Comment by acka47** [comment]
> Then the content of `altLabel` should also be visible on the concept's page.

Thanks for the request. I opened an issue at #142 .

**Comment by TobiasNx** [comment]
Also notation is not indexed. See #161

**Comment by acka47** [comment]
With using the "full" tokenizer with https://github.com/skohub-io/skohub-vocabs/pull/180 adding more fields could blow up index size for bigger vocabs with lots of alt labels and maybe long `scopeNote` texts. We will have to take this into account when addressing this.

**Comment by sroertgen** [comment]
This could also be configured with the config file #185

**Comment by sroertgen** [comment]
#267 also suggested to search for definitions

To summarize, these fields are wanted to be searched additional to `skos:prefLabel`:

- `skos:altLabel`
- `skos:example`
- `skos:notation`
- `skos:definition`

This might blow up the index clients have to download. @acka47 maybe we are now reaching the point, where we need support for a dedicated search engine.

Tasks:

- [ ] make search fields configurable
- [ ] check size of created index
- [ ] (maybe add a dedicated search engine)

**Comment by acka47** [comment]
> maybe we are now reaching the point, where we need support for a dedicated search engine

Yes. I could imagine the following approach:

- using FlexSearch for smaller vocabs, e.g. value lists (something like up to 50 concepts)
- for larger vocabs, implement lookup via the reconciliation API suggest endpoint (reconciliation support only makes sense after a certain amount of concepts anyway)

**Comment by sroertgen** [comment]
To work on this issue I decided to first fix #186.

This was long due and will help us on this issue.

Question I have is: How do we want to show the user that a concept matches though it is not the skos:prefLabel that matches?

I'm thinking of displaying the concept in italics and then maybe providing something like a tooltip?

Any other suggestions? Will post something here when I have a first prototype

**Comment by acka47** [comment]
What about somehow adding the field in brackets after the preflabel, like:

Search for "dialekt" in https://test.skohub.io/hbz/lobid-vocabs/heads/master/nwbib.de/subjects.de.html:

Show:
- [740000 Sprache](https://test.skohub.io/hbz/lobid-vocabs/heads/master/nwbib.de/subjects.de.html#N740000)
   - [744000 Mundarten](https://test.skohub.io/hbz/lobid-vocabs/heads/master/nwbib.de/subjects.de.html#N744000) (Alt Label: Dialekt)

**Comment by sroertgen** [comment]
![image](https://github.com/skohub-io/skohub-vocabs/assets/18149685/81cc54dc-7958-45e3-b610-07e83f2515dc)

I think I'm pretty close. I just asked myself why just:

- skos:altLabel 
- skos:example
- skos:notation
- skos:definition

shouldn't hiddenLabel, scopeNote and note be searchable as well?

**Comment by sroertgen** [comment]
tagging also @carlschuurbiers if he has any opinions on that

**Comment by carlschuurbiers** [comment]
sure, that would be very useful, I think if one is searching for some expression, you will probably want to look everywhere. I only hope it will not clutter the interface too much if you add a checkbox for every expression... But it is a great feature!

**Comment by carlschuurbiers** [comment]
is it possible to highlight the other places where an expression was found in the right window? So if nothing is highlighted in the left window, one can click on the entry and in the right window, where all data is displayed, the corresponding text is highlighted?

adding just the altLabel in the left window is great though. But we can't add all labels there...
