### ISSUE TITLE
Show altLabel on concept page

### ISSUE THREAD

**Issue by acka47** [skohub-io/skohub-vocabs#142]
Requested in https://github.com/skohub-io/skohub-vocabs/issues/128#issuecomment-857844413.

Currently, `altLabel` information is not shown in the HTML, see e.g. http://w3id.org/kim/schulfaecher/s1028 where you can find two altLabels in the JSON.

**Comment by sroertgen** [comment]
how do we want to display the altLabels? as a list?

![Screenshot 2021-08-30 at 16 37 20](https://user-images.githubusercontent.com/18149685/131356695-4f3dd467-7ad3-4f2c-bfe5-2efa05a039df.png)

**Comment by acka47** [comment]
Looks finde to me and is in line with the current UI approach, so +1.
