### ISSUE TITLE
Don't display collapsing / expand button for flat lists

### ISSUE THREAD

**Issue by nichtich** [skohub-io/skohub-vocabs#148]
This extends #27. See for instance <https://skohub.io/dini-ag-kim/license/heads/main/w3id.org/kim/license/index.de.html>.

**Comment by sroertgen** [comment]
I don't see any buttons. Can someone provide a screenshot?

**Comment by acka47** [comment]
> I don't see any buttons. Can someone provide a screenshot?

There you go:

[![Bildschirmfoto vom 2021-09-01 16-53-46](https://user-images.githubusercontent.com/160292/131694566-641f754c-e4f3-4c28-aa83-0195440a54ce.png)](https://skohub.io/dini-ag-kim/license/heads/main/w3id.org/kim/license/index.de.html)

**Comment by sroertgen** [comment]
ups...
I can see clearly now...
https://www.youtube.com/watch?v=MrHxhQPOO2c
