### ISSUE TITLE
Migrate Gatsby and update dependencies

### ISSUE THREAD

**Issue by sroertgen** [skohub-io/skohub-vocabs#162]
I would like to update our dependencies and noticed that Gatsby is now at V4. 
We are currently still at V2.

Migrating to V3 does not seem to have any further issues for us.

Migrating to V4 means that we have to use Node >= 14.15.0 (https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v3-to-v4/#minimal-nodejs-version-14150). Would that be a problem for any one? @acka47 @dr0i

**Comment by dr0i** [comment]
If the update works on your local installation it should work at ours, too. I don't have any problems with that, then.
