### ISSUE TITLE
Skohub-vocab does not build in fork repository but builds in cloned repo

### ISSUE THREAD

**Issue by dchoi127** [skohub-io/skohub-vocabs#177]
When running "npm run build" in a cloned repository the schema construction works as intended. However, when running "npm run build" in a forked repository the schema construction terminates with the error message below. 

<img width="627" alt="Screen Shot 2022-03-30 at 9 51 29 PM" src="https://user-images.githubusercontent.com/93415557/160960365-75774019-adf3-41f7-802d-0fceecbc5058.png">\

With the error lying in url-template.js, I used the diff command to observe if there were any differences between the url-template.js in the forked repository vs the cloned repository. Strangely enough, the diff command returned that there were no differences. 

IMPORTANT NOTE: The files in src/common.js and the data directory were changed slightly. Changes seen in https://github.com/skohub-io/skohub-vocabs/issues/176 . However, I do not see these changes causing a problem. Is there something I am overlooking? 

The forked repository link: https://github.com/dchoi127/skohub-vocabs

**Comment by acka47** [comment]
I can not reproduce this. It worked fine for me with node v16.13.1:

1. Fork to https://github.com/acka47/skohub-vocabs
2. `$ git clone git@github.com:acka47/skohub-vocabs.git skohub-vocabs-forked-test`
3. `$ cd skohub-vocabs-forked-test`
4. `$ nvm use 16`
5. `$ npm i`
6. `$ cp .env.example .env`
7. `$ cp test/data/systematik.ttl data/`
8. `$ rm -rf .cache` (which is probably unnecessary at this point)
9. `$ npm run build`
10. `$ cd public/`
11. `$ python3 -m http.server`
12. Open http://0.0.0.0:8000/w3id.org/class/hochschulfaecher/scheme.de.html in browser et voilà

![image](https://user-images.githubusercontent.com/160292/161029350-ce4af62b-b2ee-4eaa-accd-020a5ae5eae2.png)

**Comment by tombaker** [comment]
@acka47 The sequence above also works with node v17.8.0 and `helminths.ttl` (corrected).

**Comment by acka47** [comment]
@dchoi127 Please close the issue if your problem is resolved.

**Comment by dchoi127** [comment]
Problem was resolved. Thank you!
