### ISSUE TITLE
Implement logo, font & colour changes in SkoHub Vocabs

### ISSUE THREAD

**Issue by acka47** [skohub-io/skohub-vocabs#201]
The defeault design for a SkoHub Vocabs instance must be adjusted according to https://github.com/skohub-io/skohub.io/blob/master/skohub-branding-basics.pdf

**Comment by acka47** [comment]
@kaimertens @axenzen It became clear to me that – although we won't host a SkoHub Vocabs instance in this design ourselves – every newly installed instance does have a default design. This default design should also follow the branding requirements. I am afraid, this isn't covered by our contract. Is there a possibility you can include it in the project anyway?

**Comment by axenzen** [comment]
Sorry for the late reply. We will adress this within the contract.

**Comment by acka47** [comment]
Thanks for the good news!
