### ISSUE TITLE
Missing context when browsing vocab

### ISSUE THREAD

**Issue by acka47** [skohub-io/skohub-vocabs#214]
When browsing a vocabulary  built with SkoHub Vocabs I a missing two things:

1. The context of the concepts, i.e. which vocab they are part of
2. An easy way to go back to the vocab description

Here are some option:
a. Solve 1.) and 2.) both by adding the vocabs name into the header and link it to the vocab description. Similar to this  but with a bigger font and the vocab name centered.
![image](https://user-images.githubusercontent.com/160292/205254924-0ea42e18-313c-48af-b4af-09df4fe79c12.png)

b. Remove "SkohubHub Vocabs" from the header and display the vocab name instead:
![image](https://user-images.githubusercontent.com/160292/205254784-c04fb8c5-d10b-4f16-ae84-00cb77c18bd2.png)

I tend toward 2.) and we should then add a "Built with [SkoHub Vocabs](https://github.com/skohub-io/skohub-vocabs)" text in the footer.

**Comment by sroertgen** [comment]
I went with 1, because with 2 it is not possible to browse back to the index page, where all concept schemes are listed.

**Comment by acka47** [comment]
Doing the functional review here: I am not yet satisfied with this solution because the vocab is listed with quite a small font size and the position is a bit out of place for a regular desktop display. There is also a third option where we would add the "in Scheme" link to each concept page. 

Maybe we should have a general discussion about this also wrt to the list of concept schemes from on e vocab. For me, it is more important to see the context when browsing a vocab than to go back to the vocab list page. This is similar to the discussion we had in the context of SkoHub Reconcile where Andreas suggested to add a list of all vocabs an endpoint offers reconciliation for. For me, I tend to think rather in the context of one vocab than about discovery of several vocabs. (I also tend to have one vocab per repo so that the list page isn't necessary anyway.)

**Comment by sroertgen** [comment]
I totally get the point. Was just guiding myself on example 1.

I like your third option. Additionally we could do something like this, maybe:

![image](https://user-images.githubusercontent.com/18149685/206193735-6e3fd0f1-b48a-4dd7-9a58-f596dbc262ad.png)

I'm open for the general discussion. I personally think the overview page is a nice feature and gets quite used by some SkoHub Vocabs users. It also feels quite natural to have the option to go back to the index / main page in the upper left corner. I guess this could also be the area, where projects could implement their name and logo, if they want.

**Comment by acka47** [comment]
+1 for following the approach in the screenshot of https://github.com/skohub-io/skohub-vocabs/issues/214#issuecomment-1340988196 for now. We should then put some general thought into this and adjust further. 

* I don't see the need to have the name of the software on such a prominent place like we have now.
* It doesn't seem intuitive that the software name links to an overview of vocabularies in the same GitHub repo.

We should invite @kaena83 to the conversation as she has some experience with UX design.

**Comment by acka47** [comment]
One last thought.

Premises:
1. My general problem is with the list showing vocabularies from one specific GitHub repo. This seems arbitrary but might encourage people to publish all their vocabs from one repo which – from my point of view – should not become best practice.
2. We want to encourage people to set up their own –institutional or personal – SkoHub Vocabs instances.

I conclude with a question:

Shouldn't the overview page then show all vocabularies published via the specific SkoHub instance, regardless of the git repo they are residing in? (With a possibility to filter the list for organisations with a larger set of vocabs.)

**Comment by sroertgen** [comment]
I opened a discussion to further discuss on this topic: https://github.com/skohub-io/skohub-vocabs/discussions/228
