### ISSUE TITLE
Setup container based development process

### ISSUE THREAD

**Issue by sroertgen** [skohub-io/skohub-vocabs#238]
The main objective is to mitigate issues arise from developers working with different operating systems.
We are using Docker for now due to the wide adoption.

## Prequisites
Having Docker Desktop or Docker Engine + Docker CLI + Docker Compose installed

## Workflow
- Update sources: `git pull`
- Spin up the container: `docker compose up`
- Doing stuff
- Commit and push your work: `git commit`and `git push` 

## Setup
- Sources on the host machine are mounted into the container. 
- The skohub-vocabs app is running in develop mode inside the container with a debian OS. 
- You can view skohub-vocabs in the browser on the host at `http://localhost:8000/index.de.html`

**Comment by Phu2** [comment]
Hot reloading aka fast refresh seems to be working well. At least for changes in the `/src` folder.
