### ISSUE TITLE
Support local namespaces

### ISSUE THREAD

**Issue by acka47** [skohub-io/skohub-vocabs#26]
It would be great to just publish a SKOS vocab on GitHub and then be able to have all the functionality in SkoHub without setting up a redirect.

## Background

I wanted to publish https://github.com/tawahle/destatis_faecherklassifikation/blob/master/faecherklassifikation.rdf with SkoHub for interested parties to inspect the vocabulary. Everything worked quite well, the classification was shown as expected. However, clicking on a concept made a problem of course, because the concept URIs (namespace https://onto.tib.eu/destf/cs/) do not redirect to SkoHub (in fact, they do not go anywhere).

As I am not in control of the domain and did not want to use another HTTP namespace where I'd have to setup a redirect myself, I tried to use a local namespaces. This did not work, and in fact sometimes even broke the other Skohub-published vocab in the repo:

- `@prefix : <#> .` did not work and broke https://test.skohub.io/acka47/skos/w3id.org/class/hochschulfaecher/scheme.html (https://github.com/acka47/skos/commit/592f0764d712bd7df2e8a00b48eb0ad1d89af3eb)
- `@prefix : <faecherklassifikation#> .` & `@prefix : </faecherklassifikation#> .` did not break the other vocab but did not work. (https://github.com/acka47/skos/commit/4abe0c6b0228818bb7d79fe531ca8c99566df75e)
- `@base </faecherklassifikation/> .` same as the previous. (https://github.com/acka47/skos/commit/27a5dfe0ff06d0bd64e007120d4839fe07e5e229)
- `@base <faecherklassifikation/> .` also broke https://test.skohub.io/acka47/skos/w3id.org/class/hochschulfaecher/scheme.html (https://github.com/acka47/skos/commit/f75a83577327f19d8b13fbd80857786d62d8bc9d)

**Comment by literarymachine** [comment]
+ 1

I had the same issue when publishing https://test.skohub.io/literarymachine/skos/purl.org/dcx/lrmi-vocabs/educationalAudienceRole/

**Comment by acka47** [comment]
Hmm, but it does work for https://test.skohub.io/literarymachine/skos/purl.org/dcx/lrmi-vocabs/educationalAudienceRole/. What did you do differenly?

**Comment by literarymachine** [comment]
> Hmm, but it does work for https://test.skohub.io/literarymachine/skos/purl.org/dcx/lrmi-vocabs/educationalAudienceRole/. What did you do differenly?

What I meant is that I published it using a purl.org namespace without redirect configuration to skohub. What was different though, is that in my case the tree navigation used relative links. There was a bug preventing this for `https` URIs which I fixed in https://github.com/hbz/skohub-ssg/pull/22/commits/4951621d5f178561fd0b8e4a70bd937c02c831e0:

https://test.skohub.io/literarymachine/skos/onto.tib.eu/destf/cs/

**Comment by acka47** [comment]
Ok, this fixes the problem I had. Leaving the issue open nonetheless although the priority is not very high by now.

**Comment by sroertgen** [comment]
This is possible with https://github.com/skohub-io/skohub-vocabs/pull/272

You can provide a `customDomain` in the config file and it will be used to build your vocabulary.

**Comment by acka47** [comment]
Actually, I am not sure whether this really works. Reopening until I see a running example.

The use case it this:

- I want to publish a vocab on skohub.io, e.g. https://test.skohub.io/acka47/testing-skohub-vocabs/heads/master/w3id.org/kim/hochschulfaechersystematik/scheme.html
-I want to use this namespace in my turtle file: `prefix : <https://test.skohub.io/acka47/testing-skohub-vocabs/heads/master/w3id.org/kim/hochschulfaechersystematik/>` so that the URI where a concept is published in the end is the same as the one in the turtle.

I tried this at https://github.com/acka47/testing-skohub-vocabs and the build won't work. Did I do something wrong?
