### ISSUE TITLE
Include skos:definition in search index

### ISSUE THREAD

**Issue by carlschuurbiers** [skohub-io/skohub-vocabs#267]
It would be practical for the search function to also search skos:altLabel, skos:definition and the Concepts themselves.

**Comment by carlschuurbiers** [comment]
Just noticed this is partly duplicate of issue #128, sorry.

**Comment by acka47** [comment]
Thanks for the request, @carlschuurbiers , and not problem with the additonal ticket. The indexing aof `skos:altLabel` is already covered with #128 so we can discuss the integration of `skos:definition` in the search. I am not sure whether this makes sense for alle the use cases. So we should make it configurable (@sroertgen has already implemented this in #185 ) and probably not set it as default.

I am leaving this ticket open for now. @sroertgen is developing SkoHub Vocabs and he will be back in two weeks. He may close this in favour of #128 then.

**Comment by sroertgen** [comment]
I just summarized this issue in #128 and will close this one.
