### ISSUE TITLE
Vocabulary output as json fails

### ISSUE THREAD

**Issue by nanoyan** [skohub-io/skohub-vocabs#278]
Since ? two weeks, the JSON output does not work anymore. Any sub entry works, but an request to the the root of the vocab responds with an empty JSON file. This seems to happen when we change anything in our repo and the hook triggers a reload of ttl and a production of the JSON.

We did not change any ttl file, just did some adjustments of the csv files our ttl files base on. So the hook works, the ttl is drawn, but the processing seems buggy.

This blocks all of our web aplications. No one can work with our vocabs anymore.

* [old working vocab](https://skohub.io/iqb-vocabs/v56/heads/master/w3id.org/iqb/v56/le/index.de.html)
* [new buggy vocab](https://skohub.io/iqb-vocabs/v10/heads/master/w3id.org/iqb/v10/i1/index.de.html)

**Comment by sroertgen** [comment]
Can you please provide a turtle file for this vocab?
Will look at it asap

**Comment by sroertgen** [comment]
If you have access, please also attach the output of the webhook

**Comment by nanoyan** [comment]
[vocab group](https://github.com/iqb-vocabs/v10/)

The webhook takes all of three vocabs/ttl files of this repo. We've trouble with all vocabs.

Everything else works fine. Just the JSON output of the root fails.

**Comment by nanoyan** [comment]
Additional hint: The old working repos do not have the fancy icon to copy the URL of the vocab. The settings icon of the search slot seems new too.

**Comment by nanoyan** [comment]
Hi again, you are right we have an error. But I don't know why, becuase we didn't change anything on the ttls.


SkoHub SkoHub-Log
error
Mon Nov 06 2023
Payload

{
  "ref": "refs/heads/master",
  "before": "ea8044c12d0d9e2d6997874a5a06a395f4de1e53",
  "after": "b1df9ad116d98b092cff5cd43777d9fc74b21243",
  "repository": {
    "id": 698267946,
    "node_id": "R_kgDOKZ65Kg",
    "name": "v10",
    "full_name": "iqb-vocabs/v10",
    "private": false,
    "owner": {
      "name": "iqb-vocabs",
      "email": null,
      "login": "iqb-vocabs",
      "id": 105203498,
      "node_id": "O_kgDOBkVHKg",
      "avatar_url": "https://avatars.githubusercontent.com/u/105203498?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/iqb-vocabs",
      "html_url": "https://github.com/iqb-vocabs",
      "followers_url": "https://api.github.com/users/iqb-vocabs/followers",
      "following_url": "https://api.github.com/users/iqb-vocabs/following{/other_user}",
      "gists_url": "https://api.github.com/users/iqb-vocabs/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/iqb-vocabs/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/iqb-vocabs/subscriptions",
      "organizations_url": "https://api.github.com/users/iqb-vocabs/orgs",
      "repos_url": "https://api.github.com/users/iqb-vocabs/repos",
      "events_url": "https://api.github.com/users/iqb-vocabs/events{/privacy}",
      "received_events_url": "https://api.github.com/users/iqb-vocabs/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "html_url": "https://github.com/iqb-vocabs/v10",
    "description": "Vokabulare: Bildungsstandards Mathematik Primar 2022",
    "fork": false,
    "url": "https://github.com/iqb-vocabs/v10",
    "forks_url": "https://api.github.com/repos/iqb-vocabs/v10/forks",
    "keys_url": "https://api.github.com/repos/iqb-vocabs/v10/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/iqb-vocabs/v10/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/iqb-vocabs/v10/teams",
    "hooks_url": "https://api.github.com/repos/iqb-vocabs/v10/hooks",
    "issue_events_url": "https://api.github.com/repos/iqb-vocabs/v10/issues/events{/number}",
    "events_url": "https://api.github.com/repos/iqb-vocabs/v10/events",
    "assignees_url": "https://api.github.com/repos/iqb-vocabs/v10/assignees{/user}",
    "branches_url": "https://api.github.com/repos/iqb-vocabs/v10/branches{/branch}",
    "tags_url": "https://api.github.com/repos/iqb-vocabs/v10/tags",
    "blobs_url": "https://api.github.com/repos/iqb-vocabs/v10/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/iqb-vocabs/v10/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/iqb-vocabs/v10/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/iqb-vocabs/v10/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/iqb-vocabs/v10/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/iqb-vocabs/v10/languages",
    "stargazers_url": "https://api.github.com/repos/iqb-vocabs/v10/stargazers",
    "contributors_url": "https://api.github.com/repos/iqb-vocabs/v10/contributors",
    "subscribers_url": "https://api.github.com/repos/iqb-vocabs/v10/subscribers",
    "subscription_url": "https://api.github.com/repos/iqb-vocabs/v10/subscription",
    "commits_url": "https://api.github.com/repos/iqb-vocabs/v10/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/iqb-vocabs/v10/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/iqb-vocabs/v10/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/iqb-vocabs/v10/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/iqb-vocabs/v10/contents/{+path}",
    "compare_url": "https://api.github.com/repos/iqb-vocabs/v10/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/iqb-vocabs/v10/merges",
    "archive_url": "https://api.github.com/repos/iqb-vocabs/v10/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/iqb-vocabs/v10/downloads",
    "issues_url": "https://api.github.com/repos/iqb-vocabs/v10/issues{/number}",
    "pulls_url": "https://api.github.com/repos/iqb-vocabs/v10/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/iqb-vocabs/v10/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/iqb-vocabs/v10/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/iqb-vocabs/v10/labels{/name}",
    "releases_url": "https://api.github.com/repos/iqb-vocabs/v10/releases{/id}",
    "deployments_url": "https://api.github.com/repos/iqb-vocabs/v10/deployments",
    "created_at": 1695997804,
    "updated_at": "2023-10-02T12:14:03Z",
    "pushed_at": 1699283042,
    "git_url": "git://github.com/iqb-vocabs/v10.git",
    "ssh_url": "git@github.com:iqb-vocabs/v10.git",
    "clone_url": "https://github.com/iqb-vocabs/v10.git",
    "svn_url": "https://github.com/iqb-vocabs/v10",
    "homepage": "https://skohub.io/iqb-vocabs/v10/heads/master/index.de.html",
    "size": 39,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": null,
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": {
      "key": "cc-by-sa-4.0",
      "name": "Creative Commons Attribution Share Alike 4.0 International",
      "spdx_id": "CC-BY-SA-4.0",
      "url": "https://api.github.com/licenses/cc-by-sa-4.0",
      "node_id": "MDc6TGljZW5zZTI2"
    },
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master",
    "stargazers": 0,
    "master_branch": "master",
    "organization": "iqb-vocabs",
    "custom_properties": {}
  },
  "pusher": {
    "name": "nanoyan",
    "email": "yanpingchenlin@gmail.com"
  },
  "organization": {
    "login": "iqb-vocabs",
    "id": 105203498,
    "node_id": "O_kgDOBkVHKg",
    "url": "https://api.github.com/orgs/iqb-vocabs",
    "repos_url": "https://api.github.com/orgs/iqb-vocabs/repos",
    "events_url": "https://api.github.com/orgs/iqb-vocabs/events",
    "hooks_url": "https://api.github.com/orgs/iqb-vocabs/hooks",
    "issues_url": "https://api.github.com/orgs/iqb-vocabs/issues",
    "members_url": "https://api.github.com/orgs/iqb-vocabs/members{/member}",
    "public_members_url": "https://api.github.com/orgs/iqb-vocabs/public_members{/member}",
    "avatar_url": "https://avatars.githubusercontent.com/u/105203498?v=4",
    "description": ""
  },
  "sender": {
    "login": "nanoyan",
    "id": 24934443,
    "node_id": "MDQ6VXNlcjI0OTM0NDQz",
    "avatar_url": "https://avatars.githubusercontent.com/u/24934443?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/nanoyan",
    "html_url": "https://github.com/nanoyan",
    "followers_url": "https://api.github.com/users/nanoyan/followers",
    "following_url": "https://api.github.com/users/nanoyan/following{/other_user}",
    "gists_url": "https://api.github.com/users/nanoyan/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/nanoyan/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/nanoyan/subscriptions",
    "organizations_url": "https://api.github.com/users/nanoyan/orgs",
    "repos_url": "https://api.github.com/users/nanoyan/repos",
    "events_url": "https://api.github.com/users/nanoyan/events{/privacy}",
    "received_events_url": "https://api.github.com/users/nanoyan/received_events",
    "type": "User",
    "site_admin": false
  },
  "created": false,
  "deleted": false,
  "forced": false,
  "base_ref": null,
  "compare": "https://github.com/iqb-vocabs/v10/compare/ea8044c12d0d...b1df9ad116d9",
  "commits": [
    {
      "id": "b1df9ad116d98b092cff5cd43777d9fc74b21243",
      "tree_id": "88a630fbf4f589e719ae4fca75666ce9d26f321e",
      "distinct": true,
      "message": "make csv beautiful ans searchable",
      "timestamp": "2023-11-06T16:03:21+01:00",
      "url": "https://github.com/iqb-vocabs/v10/commit/b1df9ad116d98b092cff5cd43777d9fc74b21243",
      "author": {
        "name": "nanoyan",
        "email": "yanpingchenlin@gmail.com",
        "username": "nanoyan"
      },
      "committer": {
        "name": "nanoyan",
        "email": "yanpingchenlin@gmail.com",
        "username": "nanoyan"
      },
      "added": [],
      "removed": [],
      "modified": [
        "csv/a1_Anforderungsbereiche.csv",
        "csv/csv2ttl_config.json",
        "csv/i1_Inhaltsbezogene_Kompetenzen.csv",
        "csv/p1_Prozessbezogene_Kompetenzen.csv",
        "package.json"
      ]
    }
  ],
  "head_commit": {
    "id": "b1df9ad116d98b092cff5cd43777d9fc74b21243",
    "tree_id": "88a630fbf4f589e719ae4fca75666ce9d26f321e",
    "distinct": true,
    "message": "make csv beautiful ans searchable",
    "timestamp": "2023-11-06T16:03:21+01:00",
    "url": "https://github.com/iqb-vocabs/v10/commit/b1df9ad116d98b092cff5cd43777d9fc74b21243",
    "author": {
      "name": "nanoyan",
      "email": "yanpingchenlin@gmail.com",
      "username": "nanoyan"
    },
    "committer": {
      "name": "nanoyan",
      "email": "yanpingchenlin@gmail.com",
      "username": "nanoyan"
    },
    "added": [],
    "removed": [],
    "modified": [
      "csv/a1_Anforderungsbereiche.csv",
      "csv/csv2ttl_config.json",
      "csv/i1_Inhaltsbezogene_Kompetenzen.csv",
      "csv/p1_Prozessbezogene_Kompetenzen.csv",
      "package.json"
    ]
  }
}

Headers

{
  "host": "10.9.0.40:3000",
  "user-agent": "GitHub-Hookshot/2f974cb",
  "accept": "*/*",
  "x-github-delivery": "b8cffb86-7cb5-11ee-98ec-896247a0ac3f",
  "x-github-event": "push",
  "x-github-hook-id": "435826842",
  "x-github-hook-installation-target-id": "698267946",
  "x-github-hook-installation-target-type": "repository",
  "x-hub-signature": "*******************",
  "x-hub-signature-256": "sha256=3120e8f9ff0ee2b04796a0c8890a8abba64f02fced1e3cfd0121cde74bd1cbbe",
  "content-type": "application/json",
  "x-forwarded-proto": "https",
  "x-forwarded-for": "140.82.115.145",
  "x-forwarded-host": "skohub.io",
  "x-forwarded-server": "skohub.io",
  "content-length": "8309",
  "connection": "close"
}

Deploy log

    16:04:08

    > skohub-vocabs@0.1.0 container-build
    > gatsby build --prefix-paths

    16:04:08
    ╔════════════════════════════════════════════════════════════════════════╗
    ║                                                                        ║
    ║   Gatsby collects anonymous usage analytics                            ║
    ║   to help improve Gatsby for all users.                                ║
    ║                                                                        ║
    ║   If you'd like to opt-out, you can use `gatsby telemetry --disable`   ║
    ║   To learn more, checkout https://gatsby.dev/telemetry                 ║
    ║                                                                        ║
    ╚════════════════════════════════════════════════════════════════════════╝
    16:04:11
    success compile gatsby files - 0.905s

    16:04:11
    [2K[1A[2K[Gsuccess load gatsby config - 0.058s
    16:04:11

    16:04:12
    [2K[1A[2K[Gsuccess load plugins - 0.549s

    16:04:12
    [2K[1A[2K[Gsuccess onPreInit - 0.077s

    16:04:12
    [2K[1A[2K[Gsuccess delete html and css files from previous builds - 0.028s

    16:04:12
    [2K[1A[2K[Gsuccess initialize cache - 0.264s

    16:04:13
    [2K[1A[2K[Gsuccess copy gatsby files - 0.112s

    16:04:13
    [2K[1A[2K[Gsuccess Compiling Gatsby Functions - 0.226s

    16:04:13
    [2K[1A[2K[Ginfo Found these turtle files:

    16:04:13
    [2K[1A[2K[Ginfo /app/data/iqb-vocabs/v10/a1_Anforderungsbereiche.ttl

    16:04:13
    [2K[1A[2K[Ginfo /app/data/iqb-vocabs/v10/i1_Inhaltsbezogene_Kompetenzen.ttl

    16:04:13
    [2K[1A[2K[Ginfo /app/data/iqb-vocabs/v10/p1_Prozessbezogene_Kompetenzen.ttl

    16:04:13
    [2K[1A[2K[Ginfo Validating:  /app/data/iqb-vocabs/v10/a1_Anforderungsbereiche.ttl

    16:04:13
    [2K[1A[2K[G
    16:04:13
    info Validation result:  false
    16:04:13

    16:04:13
    [2K[1A[2K[G
    16:04:13
    info -----------Warning--------------
     Message:  [
      Literal {
        value: 'A provided license increases reusability of a vocabulary. Should be
    an URI.',
        language: '',
        datatype: NamedNode { value: 'http://www.w3.org/2001/XMLSchema#string' }
      }
    ]
     Path:  http://purl.org/dc/terms/license
     Node, where the error occured:  https://w3id.org/iqb/v10/a1/#
     Severity of error:  http://www.w3.org/ns/shacl#Warning
    16:04:13
    info -----------Warning--------------
     Message:  [
      Literal {
        value: 'A provided license increases reusability of a vocabulary. Should be
    an URI.',
        language: '',
        datatype: NamedNode { value: 'http://www.w3.org/2001/XMLSchema#string' }
      }
    ]
     Path:  http://purl.org/dc/terms/license
     Node, where the error occured:  https://w3id.org/iqb/v10/a1/#
     Severity of error:  http://www.w3.org/ns/shacl#Warning
    16:04:13

    16:04:13
    [2K[1A[2K[G
    16:04:13
    info -----------Warning--------------
     Message:  [
      Literal {
        value: 'A preferred Namespace URI should be given as a string, especially if
     you want to use your vocabulary in reconciliation services.',
        language: '',
        datatype: NamedNode { value: 'http://www.w3.org/2001/XMLSchema#string' }
      }
    ]
     Path:  http://purl.org/vocab/vann/preferredNamespaceUri
     Node, where the error occured:  https://w3id.org/iqb/v10/a1/#
     Severity of error:  http://www.w3.org/ns/shacl#Warning
    16:04:13
    info -----------Warning--------------
     Message:  [
      Literal {
        value: 'A preferred Namespace URI should be given as a string, especially if
     you want to use your vocabulary in reconciliation services.',
        language: '',
        datatype: NamedNode { value: 'http://www.w3.org/2001/XMLSchema#string' }
      }
    ]
     Path:  http://purl.org/vocab/vann/preferredNamespaceUri
     Node, where the error occured:  https://w3id.org/iqb/v10/a1/#
     Severity of error:  http://www.w3.org/ns/shacl#Warning
    16:04:13

    16:04:13
    [2K[1A[2K[G
    16:04:13
    info Validating:  /app/data/iqb-vocabs/v10/i1_Inhaltsbezogene_Kompetenzen.ttl

    16:04:13
    [2K[1A[2K[G
    16:04:13
    info Validation result:  false

    16:04:13
    [2K[1A[2K[Ginfo -----------Warning--------------
     Message:  [
      Literal {
        value: 'A provided license increases reusability of a vocabulary. Should be
    an URI.',
        language: '',
        datatype: NamedNode { value: 'http://www.w3.org/2001/XMLSchema#string' }
      }
    ]
     Path:  http://purl.org/dc/terms/license
     Node, where the error occured:  https://w3id.org/iqb/v10/i1/#
     Severity of error:  http://www.w3.org/ns/shacl#Warning
    16:04:13
    [2K[1A[2K[Ginfo -----------Warning--------------
     Message:  [
      Literal {
        value: 'A provided license increases reusability of a vocabulary. Should be
    an URI.',
        language: '',
        datatype: NamedNode { value: 'http://www.w3.org/2001/XMLSchema#string' }
      }
    ]
     Path:  http://purl.org/dc/terms/license
     Node, where the error occured:  https://w3id.org/iqb/v10/i1/#
     Severity of error:  http://www.w3.org/ns/shacl#Warning
    16:04:13

    16:04:13
    [2K[1A[2K[G
    16:04:13
    info -----------Warning--------------
     Message:  [
      Literal {
        value: 'A preferred Namespace URI should be given as a string, especially if
     you want to use your vocabulary in reconciliation services.',
        language: '',
        datatype: NamedNode { value: 'http://www.w3.org/2001/XMLSchema#string' }
      }
    ]
     Path:  http://purl.org/vocab/vann/preferredNamespaceUri
     Node, where the error occured:  https://w3id.org/iqb/v10/i1/#
     Severity of error:  http://www.w3.org/ns/shacl#Warning

    16:04:13
    info -----------Warning--------------
     Message:  [
      Literal {
        value: 'A preferred Namespace URI should be given as a string, especially if
     you want to use your vocabulary in reconciliation services.',
        language: '',
        datatype: NamedNode { value: 'http://www.w3.org/2001/XMLSchema#string' }
      }
    ]
     Path:  http://purl.org/vocab/vann/preferredNamespaceUri
     Node, where the error occured:  https://w3id.org/iqb/v10/i1/#
     Severity of error:  http://www.w3.org/ns/shacl#Warning

    16:04:13
    [2K[1A[2K[Ginfo Validating:  /app/data/iqb-vocabs/v10/p1_Prozessbezogene_Kompetenzen.ttl

    16:04:13
    [2K[1A[2K[Ginfo Validation result:  false

    16:04:13
    [2K[1A[2K[Ginfo -----------Warning--------------
     Message:  [
      Literal {
        value: 'A provided license increases reusability of a vocabulary. Should be
    an URI.',
        language: '',
        datatype: NamedNode { value: 'http://www.w3.org/2001/XMLSchema#string' }
      }
    ]
     Path:  http://purl.org/dc/terms/license
     Node, where the error occured:  https://w3id.org/iqb/v10/p1/#
     Severity of error:  http://www.w3.org/ns/shacl#Warning

    16:04:13
    [2K[1A[2K[Ginfo -----------Warning--------------
     Message:  [
      Literal {
        value: 'A provided license increases reusability of a vocabulary. Should be
    an URI.',
        language: '',
        datatype: NamedNode { value: 'http://www.w3.org/2001/XMLSchema#string' }
      }
    ]
     Path:  http://purl.org/dc/terms/license
     Node, where the error occured:  https://w3id.org/iqb/v10/p1/#
     Severity of error:  http://www.w3.org/ns/shacl#Warning

    16:04:13
    [2K[1A[2K[Ginfo -----------Warning--------------
     Message:  [
      Literal {
        value: 'A preferred Namespace URI should be given as a string, especially if
     you want to use your vocabulary in reconciliation services.',
        language: '',
        datatype: NamedNode { value: 'http://www.w3.org/2001/XMLSchema#string' }
      }
    ]
     Path:  http://purl.org/vocab/vann/preferredNamespaceUri
     Node, where the error occured:  https://w3id.org/iqb/v10/p1/#
     Severity of error:  http://www.w3.org/ns/shacl#Warning

    16:04:13
    [2K[1A[2K[Ginfo -----------Warning--------------
     Message:  [
      Literal {
        value: 'A preferred Namespace URI should be given as a string, especially if
     you want to use your vocabulary in reconciliation services.',
        language: '',
        datatype: NamedNode { value: 'http://www.w3.org/2001/XMLSchema#string' }
      }
    ]
     Path:  http://purl.org/vocab/vann/preferredNamespaceUri
     Node, where the error occured:  https://w3id.org/iqb/v10/p1/#
     Severity of error:  http://www.w3.org/ns/shacl#Warning

    16:04:13
    [2K[1A[2K[Gsuccess onPreBootstrap - 0.887s

    16:04:14
    [2K[1A[2K[Gsuccess createSchemaCustomization - 0.004s

    16:04:14
    [2K[1A[2K[G
    16:04:14
    warn Calling `createTypes` in the `sourceNodes` API is deprecated. Please use:
    `createSchemaCustomization`.

    16:04:14
    [2K[1A[2K[G
    16:04:14
    success Clean up stale nodes - 0.004s - 0/0 0.00/s

    16:04:14
    [2K[1A[2K[G
    16:04:14
    success Checking for changed pages - 0.000s

    16:04:14
    [2K[1A[2K[G
    16:04:14
    success source and transform nodes - 0.118s

    16:04:14
    [2K[1A[2K[G
    16:04:14
    info Writing GraphQL type definitions to /app/.cache/schema.gql

    16:04:14
    [2K[1A[2K[G
    16:04:14
    success building schema - 0.375s
    16:04:14

    16:04:14
    [2K[1A[2K[G
    16:04:14
    success createPages - 0.428s
    16:04:14

    16:04:15
    [2K[1A[2K[G
    16:04:15
    success createPagesStatefully - 0.101s

    16:04:15
    [2K[1A[2K[G
    16:04:15
    info Total nodes: 235, SitePage nodes: 98 (use --verbose for breakdown)

    16:04:15
    [2K[1A[2K[G
    16:04:15
    success Checking for changed pages - 0.000s

    16:04:15
    [2K[1A[2K[G
    16:04:15
    success onPreExtractQueries - 0.000s

    16:04:16
    [2K[1A[2K[G
    16:04:16
    success extract queries from components - 1.566s

    16:04:16
    [2K[1A[2K[G
    16:04:16
    success write out redirect data - 0.001s
    16:04:16

    16:04:16
    [2K[1A[2K[G
    16:04:16
    success Build manifest and related icons - 0.117s
    16:04:16

    16:04:16
    [2K[1A[2K[G
    16:04:16
    success onPostBootstrap - 0.123s
    16:04:16

    16:04:16
    [2K[1A[2K[G
    16:04:16
    info bootstrap finished - 8.431s
    16:04:16

    16:04:16
    [2K[1A[2K[G
    16:04:16
    success write out requires - 0.004s
    16:04:16

    16:04:17
    [2K[1A[2K[Gwarn `isModuleDeclaration` has been deprecated, please migrate to
    `isImportOrExportDeclaration`
        at isModuleDeclaration
    (/app/node_modules/@babel/types/lib/validators/generated/index.js:2748:35)
        at PluginPass.Program
    (/app/node_modules/babel-plugin-lodash/lib/index.js:102:44)

    16:04:25
    [2K[1A[2K[Gsuccess Building production JavaScript and CSS bundles - 8.608s

    16:04:35
    [2K[1A[2K[G
    16:04:35
    success Building HTML renderer - 9.839s
    16:04:35

    16:04:35
    [2K[1A[2K[G
    16:04:35
    success Execute page configs - 0.089s

    16:04:35
    [2K[1A[2K[Gsuccess Caching Webpack compilations - 0.001s

    16:04:35
    [2K[1A[2K[Gsuccess run queries in workers - 0.093s - 103/103 1109.52/s

    16:04:35
    [2K[1A[2K[Gsuccess Merge worker state - 0.001s

    16:04:35
    [2K[1A[2K[Gsuccess Rewriting compilation hashes - 0.001s

    16:04:35
    [2K[1A[2K[Gsuccess Writing page-data.json and slice-data.json files to public directory -
    0.033s - 98/98 3008.96/s

    16:04:38
    [2K[1A[2K[Gsuccess Building static HTML for pages - 2.374s - 98/98 41.27/s

    16:04:38
    [2K[1A[2K[Ginfo There are no new or changed slice html files to build.
    16:04:38

    16:04:38
    [2K[1A[2K[Gsuccess stitching slices - 0.033s

    16:04:38
    [2K[1A[2K[G
    16:04:38
    success onPostBuild - 0.000s
    16:04:38

    16:04:38
    [2K[1A[2K[G

    Pages

    ┌ src/components/Concept.jsx
    │ ├   /w3id.org/iqb/v10/a1/f3q.de.html
    │ └   ...91 more pages available
    ├ src/components/ConceptScheme.jsx
    │ ├   /w3id.org/iqb/v10/a1/index.de.html
    │ └   ...2 more pages available
    ├ src/components/index.jsx
    │ └   /index.de.html
    └ src/pages/404.js
      ├   /404/
      └   /404.html

      ╭────────────────────────────────────────────────────────────────╮
      │                                                                │
      │   (SSG) Generated at build time                                │
      │ D (DSG) Deferred static generation - page generated at runtime │
      │ ∞ (SSR) Server-side renders at runtime (uses getServerData)    │
      │ λ (Function) Gatsby function                                   │
      │                                                                │
      ╰────────────────────────────────────────────────────────────────╯

    16:04:38
    [2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[Ginfo Done building in 30.665028262 sec


    Pages

    ┌ src/components/Concept.jsx
    │ ├   /w3id.org/iqb/v10/a1/f3q.de.html
    │ └   ...91 more pages available
    ├ src/components/ConceptScheme.jsx
    │ ├   /w3id.org/iqb/v10/a1/index.de.html
    │ └   ...2 more pages available
    ├ src/components/index.jsx
    │ └   /index.de.html
    └ src/pages/404.js
      ├   /404/
      └   /404.html

      ╭────────────────────────────────────────────────────────────────╮
      │                                                                │
      │   (SSG) Generated at build time                                │
      │ D (DSG) Deferred static generation - page generated at runtime │
      │ ∞ (SSR) Server-side renders at runtime (uses getServerData)    │
      │ λ (Function) Gatsby function                                   │
      │                                                                │
      ╰────────────────────────────────────────────────────────────────╯

    16:04:39
    [2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G
    16:04:39


    Hello! Will you help Gatsby improve by taking a four question survey?
    It takes less than five minutes and your ideas and feedback will be very
    helpful.


    Pages

    ┌ src/components/Concept.jsx
    │ ├   /w3id.org/iqb/v10/a1/f3q.de.html
    │ └   ...91 more pages available
    ├ src/components/ConceptScheme.jsx
    │ ├   /w3id.org/iqb/v10/a1/index.de.html
    │ └   ...2 more pages available
    ├ src/components/index.jsx
    │ └   /index.de.html
    └ src/pages/404.js
      ├   /404/
      └   /404.html

      ╭────────────────────────────────────────────────────────────────╮
      │                                                                │
      │   (SSG) Generated at build time                                │
      │ D (DSG) Deferred static generation - page generated at runtime │
      │ ∞ (SSR) Server-side renders at runtime (uses getServerData)    │
      │ λ (Function) Gatsby function                                   │
      │                                                                │
      ╰────────────────────────────────────────────────────────────────╯

    16:04:39
    [2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G
    16:04:39

    Give us your feedback here: https://gatsby.dev/feedback




    Pages

    ┌ src/components/Concept.jsx
    │ ├   /w3id.org/iqb/v10/a1/f3q.de.html
    │ └   ...91 more pages available
    ├ src/components/ConceptScheme.jsx
    │ ├   /w3id.org/iqb/v10/a1/index.de.html
    │ └   ...2 more pages available
    ├ src/components/index.jsx
    │ └   /index.de.html
    └ src/pages/404.js
      ├   /404/
      └   /404.html

      ╭────────────────────────────────────────────────────────────────╮
      │                                                                │
      │   (SSG) Generated at build time                                │
      │ D (DSG) Deferred static generation - page generated at runtime │
      │ ∞ (SSR) Server-side renders at runtime (uses getServerData)    │
      │ λ (Function) Gatsby function                                   │
      │                                                                │
      ╰────────────────────────────────────────────────────────────────╯

**Comment by sroertgen** [comment]
Thanks, these are just warnings, so it should work fine.
I will have a look at it

**Comment by nanoyan** [comment]
Thank you

**Comment by sroertgen** [comment]
The jsonld output seems fine: https://skohub.io/iqb-vocabs/v10/heads/master/w3id.org/iqb/v10/i1/index.jsonld (basically it is the same data)

**Comment by sroertgen** [comment]
Will look at it tomorrow

**Comment by nanoyan** [comment]
Thank you. We have the same issue with 
https://skohub.io/iqb-vocabs/v34/heads/master/index.de.html
https://skohub.io/iqb-vocabs/v12/heads/master/index.de.html

**Comment by sroertgen** [comment]
```ttl
@prefix n0: <https://w3id.org/iqb/v10/i1/#>. 
@prefix n1: <https://w3id.org/iqb/v10/i1/>. 
```

it has something to do with this. If you delete the hashtag and use:

```ttl
@prefix n0: <https://w3id.org/iqb/v10/i1/#>. 
@prefix n1: <https://w3id.org/iqb/v10/i1/>. 
```

I think it works as expected.
I still have to figure out why and especially why it worked before, but the `index.json` gets built like expected when removing the hashtag.

Having a slash and a hastag is also quite uncommon tbh though not forbidden I think.

**Comment by sroertgen** [comment]
Working now on test as expected: https://test.skohub.io/sroertgen/test-vocabs/heads/main/w3id.org/iqb/v10/i1/index.de.html

Will deploy to prod

**Comment by sroertgen** [comment]
Now working on prod as well: https://skohub.io/sroertgen/test-vocabs/heads/main/w3id.org/iqb/v10/i1/index.json

**Comment by sroertgen** [comment]
@nanoyan:
The issue was the following:
In the past weeks we implemented a check of the files against a shape, to make the error outputs of SkoHub Vocabs more useful. The webhook service, which you use, checks the stdout for messages containing the string `error`. Your files contain some warnings, but in the string of that warning the word `error` occurs. This leads to a failing action.

I improved that stdout parsing and your files should now build again.

Regarding the prefixes I mentioned:
```turtle
@prefix n0: <https://w3id.org/iqb/v10/i1/>. 
@prefix n1: <https://w3id.org/iqb/v10/i1/>. 
```

You are basically creating two different prefixes for the same URI. This is totally ok, but does not make too much sense. You can just use one. Still you have to remove the `#` at the end to make your vocabs work. I hope that is not too much trouble on your side.

Please check if it works now for you

**Comment by nanoyan** [comment]
Thank you. Removing # at the end works.
