### ISSUE TITLE
Problem with direct lookup of a concept

### ISSUE THREAD

**Issue by acka47** [skohub-io/skohub-vocabs#280]
The concept at question is https://test.skohub.io/hbz/lobid-vocabs/heads/master/nwbib.de/subjects.html#N448000

When I click through the hierarchy and go to this concept, everything is fine. Doing a direct lookup of the URL I get this:

![image](https://github.com/skohub-io/skohub-vocabs/assets/160292/a4fabec8-e475-45a2-a4d9-6d771160979c)

This might well be an error in the concept scheme. However, if it breaks the application we should exclude such errors in the validation process.

**Comment by acka47** [comment]
> This might well be an error in the concept scheme. 

Hmm, it doesn't look wrong to me: https://github.com/hbz/lobid-vocabs/blob/57ae3ed05324d57452fc2a3a7bee04adb3ca23e3/nwbib/nwbib.ttl#L2690-L2698

**Comment by sroertgen** [comment]
This is related to PR #279 
The test system is already serving the current dev version without the language tags

**Comment by sroertgen** [comment]
@acka47 if you visit it the second time, does it work?

**Comment by sroertgen** [comment]
Will look into it. Maybe I have overlooked something regarding hash uris

**Comment by acka47** [comment]
Investigating this further, there are neither `skos:definition` nor `skos:scopeNote` shown although they are in the SKOS file, see https://github.com/hbz/lobid-vocabs/blob/57ae3ed05324d57452fc2a3a7bee04adb3ca23e3/nwbib/nwbib.ttl#L2690-L2698

Instead it reads: 
> No scope note in language "undefined" provided.

This applies to all other concepts with`scopeNote` or `definition`, see e.g. https://test.skohub.io/hbz/lobid-vocabs/heads/master/nwbib.de/subjects.html#N124000 or https://test.skohub.io/hbz/lobid-vocabs/heads/master/nwbib.de/subjects.html#N865020

Apparently, this is a problem with https://github.com/skohub-io/skohub-vocabs/pull/279, so this should be considered as part of the review of #279.

**Comment by acka47** [comment]
>  if you visit it the second time, does it work?

Yes, in the sense that there is no error message, no in the sense that `definition` and `scopeNote` are not shown.

**Comment by sroertgen** [comment]
The before mentioned problem should now also be fixed. If you rebuild, the vocab should behave like expected again

**Comment by sroertgen** [comment]
@acka47 Is this still an issue?
Direct lookup of concepts seem to be working.

**Comment by acka47** [comment]
I think this was fixed some time ago and works now like a charme: https://skohub.io/hbz/lobid-vocabs/heads/testingSkoHub/nwbib.de/subjects.html#N448000

Closing.
