### ISSUE TITLE
Concepts on non-top hierarchy levels not loading for hash URI vocab

### ISSUE THREAD

**Issue by acka47** [skohub-io/skohub-vocabs#307]
See https://skohub.io/hbz/lobid-vocabs/heads/rpbImprovements/purl.org/lobid/rpb.html and click on any concept on second or third level. This is really strange as it works for the [equivalent NWBib vocab](https://skohub.io/hbz/lobid-vocabs/heads/rpbImprovements/nwbib.de/subjects.html). The only difference between the two I could quickly see is that one uses `skos:broader` while the other uses `skos:narrower`.

Edit: The error is also in the `master` version: https://skohub.io/hbz/lobid-vocabs/heads/master/purl.org/lobid/rpb.html

**Comment by acka47** [comment]
> The only difference between the two I could quickly see is that one uses `skos:broader` while the other uses `skos:narrower`.

I removed all `broader`statements from the vocab so that it only has `narrower`: No change, see https://skohub.io/hbz/lobid-vocabs/heads/removeBroader/purl.org/lobid/rpb.html

**Comment by sroertgen** [comment]
I think this is because `skos:inScheme` statements are missing for non-topLevel Concepts.

A quick test showed that after adding such a statement to a nested concept it is working like expected.

**Comment by acka47** [comment]
> I think this is because `skos:inScheme` statements are missing for non-topLevel Concepts.

Yes, that's it. Thanks! See https://skohub.io/hbz/lobid-vocabs/heads/master/purl.org/lobid/rpb.html.

I have opened https://github.com/skohub-io/skohub-shapes/issues/21 to add an according check to the Shacl validation.
