### ISSUE TITLE
Offer vocab list page per user/organization 

### ISSUE THREAD

**Issue by acka47** [skohub-io/skohub-vocabs#66]
This was addressed in today's meeting by the OER metadata group of DINI AG KIM. It would be nice to have an overview of all vocabs published with SkoHub by a particular GitHub/GitLab organization or user. For example, at https://skohub.io/hbz/ should be a list of all vocabs from https://skohub.io/hbz/vocabs-edu/ and https://skohub.io/hbz/lobid-vocabs/ (where currently nothing is listed so that this is not a good example but I don't know a better one).

**Comment by sroertgen** [comment]
@acka47 I think this is somewhat done with https://github.com/skohub-io/skohub-webhook/commit/94eaf6901e30bb59181c50768474cfbbb1ea2871

Please close if ok
