### ISSUE TITLE
Make inboxes optional

### ISSUE THREAD

**Issue by acka47** [skohub-io/skohub-vocabs#75]
For small controlled vocabularies like the ["Audience Role" vocab](https://skohub.io/acka47/lrmi-audience-role/heads/master/purl.org/dcx/lrmi-vocabs/educationalAudienceRole/index.html) it might not really make sense to have an inbox for each element. Thus, it would be nice to be able to turn off inboxes and SkoHub pubsub functions. 

@literarymachine, we have talked about a Yaml config file in the repo along with a vocabulary. This would be a good place for configuring this. (I think each `ttl` file could have a `yml` file with the same name.)

**Comment by literarymachine** [comment]
> I think each ttl file could have a yml file with the same name.

Why? Do you assume that a vocabulary is always contained in exactly one `ttl` file?

**Comment by acka47** [comment]
> Do you assume that a vocabulary is always contained in exactly one ttl file?

Yes, I actually did. But this might be an unnecessary constraint. Then one should probably just set in the config file to which vocab(s) it belongs.

**Comment by acka47** [comment]
SkoHub PubSub (as well as SkoHub Editor) hasn't been used in production settings yet. Because of this and because of missing resources we'd need for maintenacne, we decided to switch off both modules on skohub.io for an indefinite period. 

Against this background, we should better cleanly remove all PubSub related functions from SkoHub Vocabs, which are at least these:

- [ ] `jsonas`, `inbox` and `followers` stuff in `gatsby-node.js`, `src/queries.js`, `/.env.example`, `src/common.js`, `/src/types.js`
- [ ] inbox link in `/src/components/Concept.js`
- [ ] inbox mention in `README.md`
