### ISSUE TITLE
Provide means to validate SKOS turtle files for SkoHub compliance 

### ISSUE THREAD

**Issue by acka47** [skohub-io/skohub-vocabs#91]
This might be used to add test to a GitHub repo that let you know whether your SKOS vocab is "SkoHub-ready".

**Comment by acka47** [comment]
We should not only provide a shape but also a setup for automatic testing in a GitHub repo.

**Comment by acka47** [comment]
We should probably also add [Skosify](https://github.com/NatLibFi/Skosify) and/or [qSKOS](https://github.com/cmader/qSKOS/) into the automatic test pipeline. As this might mitigate a lot of errors (plus the ones SkoHub doesn't care about, see https://github.com/dini-ag-kim/hochschulfaechersystematik/issues/24 & https://github.com/dini-ag-kim/hochschulfaechersystematik/issues/25) we might check these first.

**Comment by sroertgen** [comment]
I created a repo to work on the shape since I think it might be good to have the shape separate from code: https://github.com/skohub-io/shapes

**Comment by sroertgen** [comment]
I created a github-workflow which will validate all changed ttl files and will fail if one turtle file does not validate against the shape. You can try it out by forking this repo and playing around with the .ttl files: https://github.com/sroertgen/test-vocabs

Now I'm actually unsure on how to proceed. Should we create a template-vocab-repo, where we have this action and the scripts added a maybe a basic instruction on how to write a SKOS-file? Then we could advertise this as the starting point to develop vocabularies and have a mechanism to validate as well.

@acka47  What do you think?

**Comment by acka47** [comment]
> Should we create a template-vocab-repo, where we have this action and the scripts added a maybe a basic instruction on how to write a SKOS-file? Then we could advertise this as the starting point to develop vocabularies and have a mechanism to validate as well.

Sounds good to me. Most urgent is the inclusion of this step in the [docker version of SkoHub Vocabs](https://github.com/skohub-io/skohub-docker-vocabs), though, isn't it?

**Comment by sroertgen** [comment]
A note to my future self:

When we are sure on how to proceed, we should add a note in the README on how to validate SKOS files

**Comment by sroertgen** [comment]
I added information on how to validate SKOS vocabs here: https://github.com/skohub-io/skohub-vocabs/tree/91-validate-skos#validation-of-skos-vocabularies

**Comment by sroertgen** [comment]
I think to close this we have to do the following steps:

- [ ] move the docker image used for automatic validation into skohub namespace
- [ ] adjust the script in the vocab-template repo
- [ ] add info about validation with docker here: https://github.com/skohub-io/shapes/#check-with-docker
