### ISSUE TITLE
Do not require "narrower" statements

### ISSUE THREAD

**Issue by acka47** [skohub-io/skohub-vocabs#99]
From #85. Currently, `narrower` statements are required in the turtle file for hierarchical relationships being shown in the UI, `broader` are not. It would be good if you could choose only one of both and the vocab would build as expected.

**Comment by sroertgen** [comment]
I added a little "skosifying" in [this branch](https://github.com/skohub-io/skohub-vocabs/tree/99-narrower-broader). It seems to work and adds `skos:narrower` if they are not there for the corresponding `skos:broader` with some little test-file I wrote. Maybe you want to test it out?

**Comment by literarymachine** [comment]
While this works, I think I would do the "skosification" on the abstract RDF model, not the JSON-LD. See https://github.com/skohub-io/skohub-vocabs/pull/120/files

**Comment by sroertgen** [comment]
I favour your approach. See https://github.com/skohub-io/skohub-vocabs/pull/120#issuecomment-759291019
